services:
  - type: web
    name: rma-coordinator
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ../
    envVars:
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
